typography_spectrum: 0.48974417708814144
color:
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  brandStrength: 0.03561084461398423
  lightness: 0.9802932520397007
  saturation: 0.559965840773657
  rhythmicContrast: 0.20032248739153147
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6857277436647564
analytics:
  google: null
  facebook: null
  twitter: null
name: HEIDI ASHWORTH
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/dece7070-2e23-4df4-bc6a-841f41f58937.jpg'
purpose: []
