typography_spectrum: 0.8584229
color:
  brandColors:
    - '#fffffb'
    - '#fe684d'
    - '#ff9676'
    - '#fdb18f'
    - '#ffcead'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50587
analytics:
  google: null
  facebook: null
  twitter: null
name: HEIDI ASHWORTH
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/dece7070-2e23-4df4-bc6a-841f41f58937.jpg'
purpose: []
