layout_spectrum: 1
typography_spectrum: 0.8584229
color:
  saturation: 1
  lightness: 0.6827957
  brandStrength: 0.900083
  brandColors:
    - '#2F2A24'
    - '#8A8780'
    - '#D3D4CE'
    - '#B0B1AB'
    - '#FFFFFA'
  rhythmicContrast: 0.59319
name: HEIDI V. ASHWORTH
