name: HEIDI V. ASHWORTH
favicon: null
layout_spectrum: 0.50587
typography_spectrum: 0.8584229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffb'
    - '#fe684d'
    - '#ff9676'
    - '#fdb18f'
    - '#ffcead'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
