name: HEIDI V. ASHWORTH
favicon: null
layout_spectrum: 0.50587
typography_spectrum: 0.8584229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#454a44'
    - '#b7ccc7'
    - '#bd1725'
    - '#e88490'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
